CREATE DATABASE termoidraulica_fs;

CREATE USER tfs_admin WITH ENCRYPTED PASSWORD 'sasdevment';
GRANT ALL PRIVILEGES ON DATABASE termoidraulica_fs TO tfs_admin;

CREATE USER tfs_user WITH ENCRYPTED PASSWORD 'lory-gra';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO tfs_user;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO tfs_user;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO tfs_user;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO tfs_user;


CREATE TABLE Customer (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customerName VARCHAR(64) NOT NULL,
	customerSurname VARCHAR(64),
	residence VARCHAR(128),
	municipality VARCHAR(64),
	province CHAR(2),
	cap CHAR(5),
	cf CHAR(16),
	notes VARCHAR	
);

CREATE TABLE TaxRate (
	taxRate SMALLINT PRIMARY KEY,
	description VARCHAR(28)
);

CREATE TABLE Estimate (
	estimateId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customerId INT NOT NULL,
	expirationDate TIMESTAMP,
	insertDate TIMESTAMP,
	deposit FLOAT(2),
	FOREIGN KEY (customerId) REFERENCES Customer(id)
);

CREATE TABLE ItemGroup (
	itemGroupNum INT,
	estimateId INT NOT NULL,
	description VARCHAR,
	FOREIGN KEY (estimateId) REFERENCES Estimate(estimateId) ON DELETE CASCADE,
	PRIMARY KEY (itemGroupNum, estimateId)
);

CREATE TABLE Item (
	itemNum INT,
	itemGroupNum INT NOT NULL,
	estimateId INT NOT NULL,
	description VARCHAR,
	um VARCHAR(8),
	qt FLOAT(2),
	price FLOAT(2),
	discount FLOAT(2),
	taxRate SMALLINT NOT NULL,
	FOREIGN KEY (itemGroupNum, estimateId) REFERENCES ItemGroup(itemGroupNum, estimateId) ON DELETE CASCADE,
	FOREIGN KEY (taxRate) REFERENCES TaxRate(taxRate),
	PRIMARY KEY (itemNum, itemGroupNum, estimateId)	
);

CREATE TABLE Receipt (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	foreignId VARCHAR(16),
	description VARCHAR(28),
	date TIMESTAMP,
	taxRate SMALLINT,
	FOREIGN KEY (taxRate) REFERENCES TaxRate(taxRate)
);

CREATE TABLE Riba (
	num INT,
	receipt INT NOT NULL,
	amount FLOAT(2),
	expireDate TIMESTAMP,
	paid BOOLEAN NOT NULL,
	FOREIGN KEY (receipt) REFERENCES Receipt(id) ON DELETE CASCADE,
	PRIMARY KEY (receipt, num)
);

INSERT INTO TaxRate (taxRate, description) VALUES (22, 'Ordinaria'),
                                                  (10, 'Ridotta'),
                                                  (4, 'Minima'),
                                                  (0, 'Esente');